[[HAMdetector_model_binaries]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d9bbd4317f35c2c2a496868be3ecc31dc077e6f"
libc = "glibc"
os = "linux"

    [[HAMdetector_model_binaries.download]]
    sha256 = "60509d4096f29dc06fe71fa1431ec387ab02a665e70e9cf112236aaf0e4f0264"
    url = "https://github.com/HAMdetector/HAMdetector_model_binaries_jll.jl/releases/download/HAMdetector_model_binaries-v0.1.1+0/HAMdetector_model_binaries.v0.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HAMdetector_model_binaries]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4aec815dd23145e41a28830cf91d16104a579d5"
libc = "glibc"
os = "linux"

    [[HAMdetector_model_binaries.download]]
    sha256 = "5351964ef1e013369eccd94c95a6da546ae01824c2a2a6119a9500eff2322e22"
    url = "https://github.com/HAMdetector/HAMdetector_model_binaries_jll.jl/releases/download/HAMdetector_model_binaries-v0.1.1+0/HAMdetector_model_binaries.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
