# Autogenerated wrapper script for HAMdetector_model_binaries_jll for x86_64-linux-gnu-cxx03
export libtbb, libtbbmalloc, libtbbmalloc_proxy, model_1, model_2, model_3, model_4

JLLWrappers.@generate_wrapper_header("HAMdetector_model_binaries")
JLLWrappers.@declare_library_product(libtbb, "libtbb.so.2")
JLLWrappers.@declare_library_product(libtbbmalloc, "libtbbmalloc.so.2")
JLLWrappers.@declare_library_product(libtbbmalloc_proxy, "libtbbmalloc_proxy.so.2")
JLLWrappers.@declare_executable_product(model_1)
JLLWrappers.@declare_executable_product(model_2)
JLLWrappers.@declare_executable_product(model_3)
JLLWrappers.@declare_executable_product(model_4)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtbb,
        "lib/libtbb.so.2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtbbmalloc,
        "lib/libtbbmalloc.so.2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtbbmalloc_proxy,
        "lib/libtbbmalloc_proxy.so.2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        model_1,
        "bin/model_1",
    )

    JLLWrappers.@init_executable_product(
        model_2,
        "bin/model_2",
    )

    JLLWrappers.@init_executable_product(
        model_3,
        "bin/model_3",
    )

    JLLWrappers.@init_executable_product(
        model_4,
        "bin/model_4",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
